FROM juhp/fedora-haskell-ghc:8.0.2
RUN dnf -y install xz-devel zlib-devel glib2-devel gobject-introspection-devel ostree-devel sqlite-devel && dnf clean all

ENV PATH ~/.cabal/bin:$PATH

RUN cabal update

COPY importer /root/bdcs/importer/

RUN cabal update && cabal install happy && \
    cd /root/bdcs/importer && cabal install && cabal clean && \
    cd /root/.cabal && rm -rf lib logs packages
