FROM juhp/fedora-haskell-ghc:7.10.3
RUN dnf -y install xz-devel zlib-devel && dnf clean all

RUN cabal update

COPY haskell-rpm /root/bdcs/haskell-rpm/
COPY db-test /root/bdcs/db-test/

RUN cd /root/bdcs/haskell-rpm && cabal update && cabal install && cabal clean && \
    cd /root/bdcs/db-test && cabal update && cabal install && cabal clean && \
    cd /root/.cabal && rm -rf lib logs packages
