#!/usr/bin/env python

import sys
import urllib
import xml.etree.ElementTree as ET

if __name__ == "__main__":
    repo_url = sys.argv[1]
    response = urllib.urlopen(repo_url + '/repodata/repomd.xml')
    xml = response.read()
    xml = ET.fromstring(xml)
    for data in xml:
        if data.tag.endswith('data') and 'type' in data.attrib and \
           data.attrib['type'] == 'primary':
            break
    else:
        raise Exception('Cannot find primary.xml')

    for child in data:
        if child.tag.endswith('location'):
            print repo_url + '/' + child.attrib['href']
