#!/bin/bash -x
# This script will configure the cabal sandbox to
# use pre-release versions of codec-rpm/content-store tarballs
# instead of downloading from Hackage.
#
# It must be executed from the main project directory!
#
# Jenkins is responsible for downloading all the upstream
# artifacts to the local directory.
#
# For bdcs upstream dependencies are codec-rpm and content-store!

for dependency in codec-rpm content-store; do
    tarball="$dependency-latest.tar.gz"
    if [ -f "$tarball" ]; then
        tar -xzvf $tarball
        dir_name=`readlink -f $dependency-*/`
        cabal sandbox add-source $dir_name
    fi
done
