#!/bin/bash
# This script will configure the cabal sandbox to
# use pre-release versions of codec-rpm/content-store tarballs
# instead of downloading from Hackage.
#
# It must be executed from the main project directory!
#
# This script is executed by Jenkins when an upstream artifact
# is present.
#
# For bdcs upstream dependencies are codec-rpm and content-store!

cabal update
cabal sandbox init


for dependency in codec-rpm content-store; do
    tarball="$dependency-latest.tar.gz"
    if [ -f "$tarball" ]; then
        tar -xzvf tarball
        dir_name=`readlink -f $dependency-*/`
        cabal sandbox add-source $dir_name
    fi
done
