name = "glusterfs"
description = "An example GlusterFS server with samba"

[[modules]]
name = "glusterfs"
version = "3.7.*"

[[modules]]
name = "glusterfs-cli"
version = "3.7.*"

[[packages]]
name = "samba"
version = "4.2.*"
